import rtconfig
Import('RTT_ROOT')
from building import *

src_bsp = ['application.c', 'startup.c', 'board.c', 'lowlevel.S','console.c','sst39vfxx_mtd_sim.c']
src	= File(src_bsp)
if GetDepend('RT_USING_DFS') == False:
    SrcRemove(src, 'sst39vfxx_mtd_sim.c')
CPPPATH = [GetCurrentDir()]
group = DefineGroup('Startup', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
