# for module compiling
import os
Import('remove_components')
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

for item in list:
    if item in remove_components:
        continue

    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

# For zmodem
if GetDepend(['RT_USING_ZMODEM']):
	objs += Glob('./utilities/zmodem/*.c')

Return('objs')
