Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'Drivers')
src	= Glob('*.c')
src += Glob('wifi_8686/*.c')
CPPPATH = [cwd]
CPPPATH += ['wifi_8686/']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
